name: Application CI
on: [push, pull_request]
permissions:
  contents: read
  packages: write
jobs:
  pipeline:
    name: cicdhub pipeline
    runs-on: onprem
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
    timeout-minutes: 40
    env:
      NODE_VERSION: 22.15.0
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
      JHI_DISABLE_WEBPACK_LOGS: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.15.0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Install Node.js packages
        run: npm install
      - name: Install Snyk CLI
        run: |
          curl --compressed https://static.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x snyk
      - name: Snyk test
        continue-on-error: true
        run: ./snyk test --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Snyk monitor
        continue-on-error: true
        run: ./snyk monitor --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Run backend test
        run: |
          chmod +x mvnw
          npm run ci:backend:test
      - name: Run frontend test
        run: npm run ci:frontend:test
      - name: Analyze code with SonarQube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          if [ ! -z "$SONAR_TOKEN" ]; then
              ./mvnw -ntp initialize sonar:sonar -Dsonar.organization=cicdhub -Dsonar.host.url=https://sonarcloud.io
          else
              echo No SONAR_TOKEN, skipping...
          fi
      - name: Package application
        run: npm run java:jar:prod
      - name: Build and publish docker image
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
        run: |
          GIT_TAG=:${GITHUB_REF#refs/tags/}
          DOCKER_TAG=${GIT_TAG#:refs/heads/main}
          # ./mvnw -ntp jib:build -Djib.to.image=vidhya03/cicdhub-image${DOCKER_TAG} -Djib.to.auth.username="${{ secrets.DOCKER_USERNAME }}" -Djib.to.auth.password="${{ secrets.DOCKER_PASSWORD }}" -Pprod
          ./mvnw -ntp jib:build -Djib.to.image=ghcr.io/vidhya03/cicdhub${DOCKER_TAG} -Djib.to.auth.username="${{ github.actor }}" -Djib.to.auth.password="${{ secrets.GITHUB_TOKEN }}" -Pprod
      - name: Trigger Render deployment
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "Triggering Render deploy..."
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
          echo "Render deploy triggered!"
